"""Remove the pairing table.

Revision ID: 13914969c20a
Revises: 1415c981a9c8
Create Date: 2023-07-18 10:53:35.939494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13914969c20a'
down_revision = '1415c981a9c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Pairing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pairing',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('drug_set_id', sa.INTEGER(), nullable=False),
    sa.Column('target_set_id', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['drug_set_id'], ['DrugSet.id'], ),
    sa.ForeignKeyConstraint(['target_set_id'], ['TargetSet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
