"""Add a count column to the set tables.

Revision ID: 1415c981a9c8
Revises: 88f379fb9770
Create Date: 2023-07-13 15:32:30.332473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1415c981a9c8'
down_revision = '88f379fb9770'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DrugSet', sa.Column('count', sa.Integer(), nullable=True))
    op.add_column('TargetSet', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TargetSet', 'count')
    op.drop_column('DrugSet', 'count')
    # ### end Alembic commands ###
