"""Create the featurizer-output tables.

Revision ID: 23aedf0c3b35
Revises: d0db1cc2f9cd
Create Date: 2023-07-18 13:18:57.726699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23aedf0c3b35'
down_revision = 'd0db1cc2f9cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DrugFeaturizerOutput',
    sa.Column('smiles_string', sa.String(length=65536), nullable=False),
    sa.Column('morgan_fingerprint_output', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('smiles_string')
    )
    op.create_table('TargetFeaturizerOutput',
    sa.Column('sequence', sa.String(length=65536), nullable=False),
    sa.Column('protbert_output', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TargetFeaturizerOutput')
    op.drop_table('DrugFeaturizerOutput')
    # ### end Alembic commands ###
