"""Add a model status column to the pairing table.

Revision ID: 28344355568d
Revises: 7d36484eafc7
Create Date: 2023-07-22 00:05:21.555473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28344355568d'
down_revision = '7d36484eafc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Pairing', sa.Column('model_status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='taskstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Pairing', 'model_status')
    # ### end Alembic commands ###
