"""Add a task status column to the set tables.

Revision ID: 49539f93c63d
Revises: 23aedf0c3b35
Create Date: 2023-07-18 14:22:11.495421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49539f93c63d'
down_revision = '23aedf0c3b35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DrugSet', sa.Column('featurizer_status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='taskstatus'), nullable=True))
    op.add_column('TargetSet', sa.Column('featurizer_status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='taskstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TargetSet', 'featurizer_status')
    op.drop_column('DrugSet', 'featurizer_status')
    # ### end Alembic commands ###
