"""Add a count column to the set tables.

Revision ID: 6a6a73daa116
Revises: 88f379fb9770
Create Date: 2023-07-13 10:42:07.374852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6a73daa116'
down_revision = '88f379fb9770'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DrugSet', sa.Column('count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('TargetSet', sa.Column('count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TargetSet', 'count')
    op.drop_column('DrugSet', 'count')
    # ### end Alembic commands ###
