"""Create the pairing table.

Revision ID: 88f379fb9770
Revises: 062fa901cdd3
Create Date: 2023-07-11 10:04:39.665709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f379fb9770'
down_revision = '062fa901cdd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pairing',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('drug_set_id', sa.Integer(), nullable=False),
    sa.Column('target_set_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drug_set_id'], ['DrugSet.id'], ),
    sa.ForeignKeyConstraint(['target_set_id'], ['TargetSet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Pairing')
    # ### end Alembic commands ###
